# Ansible playbook for deploying a MySQL
---
- name: Install and Configure MySQL
  hosts: mysql
  become: yes
  become_method: sudo
  gather_facts: yes
 
  tasks:
  - name: ubuntu | Updating the package database
    apt: update_cache=yes
    ignore_errors: True

  - name: mysql | Install MySQL Packages
    apt:
      name: ['mysql-server','mysql-client','python-mysqldb','python-mysqldb','python3-pip']
      state: latest

# this is the required pip package with python3
  - name: pip | Install python MySQL Packages    
    pip:
        name: PyMySQL

  - name: mysql | Start the MySQL service
    become: true
    service: 
      name: mysql 
      state: started
      enabled: true
       
  - name: mysql | Configure mysql to listen to external interface
    lineinfile:
      dest: /etc/mysql/my.cnf
      line: '{{ item }}'
      state: present
      insertafter: EOF
    with_items:
      - '[mysqld]'
      - 'bind-address = 0.0.0.0'
      - 'bind-address = ::'
    notify:
    - restart mysql

#Imp to use `login_unix_socket` as MySQL user is set to authenticate using the auth_socket initially
  - name: mysql | Update mysql root password and allow listen from external hosts
    become: true
    mysql_user: 
      name: root 
      host: '{{ item }}'
      password: "{{ mysql_root_password }}"
      login_user: root
      login_password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - '%'
      - '127.0.0.1'
      - '::1'
      - 'localhost'
      - '0.0.0.0'
    notify:
    - restart mysql

  - name: mysql | Create database
    mysql_db:
      name: '{{ db_name }}'
      login_user: root
      login_password: '{{ mysql_root_password }}'
      state: present

  - name: mysql | Copy create table dump file
    copy:
      src: create_table.sql
      dest: /tmp

  - name: mysql | Create table
    mysql_db: 
      name: '{{ db_name }}'
      login_user: root
      login_password: '{{ mysql_root_password }}'
      state: import
      target: /tmp/create_table.sql

  handlers:
  - name: restart mysql
    service:
      name: mysql
      state: restarted
